### ISSUE TITLE
Bouncer and Spatie ?

### ISSUE THREAD

**Issue by JFOC** [LaravelDaily/laravel-roles-permissions-manager#1]
Hi,
How is this compare with Bouncer ?
Spatie version is better than Bouncer ?

**Comment by PovilasKorop** [comment]
@JFOC currently writing a whole battle/review article on the subject, follow twitter @DailyLaravel for news.

**Comment by hawkleaf** [comment]
@JFOC Check this out https://laravel-news.com/two-best-roles-permissions-packages

**Comment by PovilasKorop** [comment]
Thank you @JFOC - forgot to link it here. Closing the issue.
