### ISSUE TITLE
PHP Version Issue

### ISSUE THREAD

**Issue by meet1shah** [LaravelDaily/laravel-roles-permissions-manager#11]
When i run composer install i got this error

  Problem 1
    - Installation request for doctrine/annotations v1.6.0 -> satisfiable by doc
trine/annotations[v1.6.0].
    - doctrine/annotations v1.6.0 requires php ^7.1 -> your PHP version (7.0.25)
 does not satisfy that requirement.

How can i get rid of this without updating PHP version

**Comment by LaravelDaily** [comment]
@meet1shah some of the packages apparently requires `doctrine/annotations` v 1.6 which requires PHP 7.1. Check all the requirements in `composer.json` and probably you need to lower version for one of them, but not sure which one.

**Comment by meet1shah** [comment]
I check in composer.json file and found that
"require": {
        "php": ">=7.0.0",
        "doctrine/dbal": "^2.5",
        "intervention/image": "^2.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.3",
        "spatie/laravel-permission": "^2.2",
        "filp/whoops": "~2.0"
    },

And my current PHP version is 7.0.25

**Comment by LaravelDaily** [comment]
@meet1shah yes so one of those requirements should have lower version, not sure which one, you need to test and find yourself. Check each of those packages composer.json and see where `doctrine/annotations` is a dependency, maybe `doctrine/dbal`?

**Comment by meet1shah** [comment]
Resolved. I change PHP and laravel version in composer.json
