### ISSUE TITLE
using on existing project?

### ISSUE THREAD

**Issue by protected22** [LaravelDaily/laravel-roles-permissions-manager#13]
How can I use it on an existing project without removing these files?

**Comment by PovilasKorop** [comment]
It wasn't built to use in existing project, it's more like demo project in itself.

**Comment by PovilasKorop** [comment]
It is possible, you need to merge manually and we don't give any guarantee that it will work.

**Comment by ultrono** [comment]
@protected22 There's not a huge amount to migrate over. The logic to manage permissions/roles/users can be seen [here](https://github.com/LaravelDaily/laravel-roles-permissions-manager/tree/master/app/Http/Controllers/Adminl). The associated views are available [here](https://github.com/LaravelDaily/laravel-roles-permissions-manager/tree/master/resources/views/admin).
