### ISSUE TITLE
Problem in the sidebar

### ISSUE THREAD

**Issue by gustavocolombelli** [LaravelDaily/laravel-roles-permissions-manager#14]
Hi, i found a little bug, do you know how can i fix it?

![bug](https://user-images.githubusercontent.com/8497149/39550610-457ae77e-4e38-11e8-9d28-17ff16e2bc1d.png)

both mobile and desktop have the same error.

Thanks! 👍

**Comment by Meirimbr** [comment]
I have the same problem =(

**Comment by ModestasV** [comment]
@gustavocolombelli @Meirimbr There are quite some issues reported on the AdminLTE github:
https://github.com/almasaeed2010/AdminLTE/issues/643
https://github.com/almasaeed2010/AdminLTE/issues/1182
https://github.com/almasaeed2010/AdminLTE/issues/1547 - A bit different, but touches their scripts
https://github.com/almasaeed2010/AdminLTE/issues/1143 - Sidebar opening issues
List of all issues there:
https://github.com/almasaeed2010/AdminLTE/issues?utf8=%E2%9C%93&q=full+height+

---

All in all, the suggestions vary from one issue to another. For me personally applying these styles worked but after page refresh or data changes - it breaks:

<style>
    html { height: 100%; }
    body { height: 100%; }
</style>

On the other hand, this system does not use the latest and greatest of the Admin-LTE version where it could have been fixed. So, I'd suggest updating the theme, if that does not work - changing the resizing script to update sidebar height.
