### ISSUE TITLE
PDO::ATTR_STATEMENT_CLASS requires

### ISSUE THREAD

**Issue by prodhan** [LaravelDaily/laravel-roles-permissions-manager#15]
SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS requires format array(classname, array(ctor_args)); the classname must be a string specifying an existing class (SQL: select * from `users` where `email` = admin@admin.com limit 1)

**Comment by LaravelDaily** [comment]
@prodhan see potential solutions here https://stackoverflow.com/questions/48967363/laravel-pdoattr-statement-class-requires-format-arrayclassname-arrayctor-ar

**Comment by psobhanlo** [comment]
remove composer.lock and reinstall composer

**Comment by s2925534** [comment]
run the reinstall of ca-certificates and OpenSSL and it will work
