### ISSUE TITLE
Combined migrations

### ISSUE THREAD

**Issue by kamov** [LaravelDaily/laravel-roles-permissions-manager#16]
What is combined migrations, inside combined folder?
Seem all migrations table are already in another file.

**Comment by PovilasKorop** [comment]
@kamov they are related to Combined Migrations function in our QuickAdminPanel generator: https://quickadminpanel.com/blog/combined-migrations-even-after-many-crud-changes/

For the purpose of this demo project, they are pretty useless, ignore them.

**Comment by kamov** [comment]
Thanks for quick reply. I understand.
Best

**Comment by kamov** [comment]
I think that this also should be removed since role_user is not used:

https://github.com/LaravelDaily/laravel-roles-permissions-manager/blob/master/app/User.php#L39

**Comment by PovilasKorop** [comment]
@kamov correct, this should probably be removed. Please submit a Pull Request for it if you can, or otherwise we will fix it some time next week.

**Comment by kamov** [comment]
Sorry I am not working on this package, I am just here to look into how you implement UI so that I can do in my project.
