### ISSUE TITLE
Redirect back with errors in the form instead of showing Permission or Role already exist on PrettyPageHandler

### ISSUE THREAD

**Issue by dreamerson** [LaravelDaily/laravel-roles-permissions-manager#18]
When i try to add an existing Role i expect it to show errors in the form but instead it shows error on the prettypagehandler.
There is already a code for this in the view   @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
I want it to display on the form itself how can i do this?

**Comment by dreamerson** [comment]
![image](https://user-images.githubusercontent.com/44630093/47766514-f7678180-dd09-11e8-9ff4-5c53327b7897.png)

**Comment by ikkebra** [comment]
Run this and try it again:

php artisan cache:forget spatie.permission.cache
php artisan cache:forget spatie.role.cache
php artisan cache:clear

**Comment by dreamerson** [comment]
tried it doesn't work. 
i just want to do it like this. just want to validate if it already exist.
![image](https://user-images.githubusercontent.com/44630093/49057667-88fbdd80-f23b-11e8-9a3e-51e5de6fde1d.png)
