### ISSUE TITLE
getting all users of same role

### ISSUE THREAD

**Issue by Ravensborn** [LaravelDaily/laravel-roles-permissions-manager#2]
this doesn't seem to work

```
public function test() {

   return  $users = User::role('administrator')->get();

}
```

it returns 
Non-static method App\User::role() should not be called statically

**Comment by PovilasKorop** [comment]
@Ravensborn not sure why you're calling this function this way, it's incorrect.
It's many-to-many relationship, so if you want to get all administrator users, it's something like this:

```
$users = User::whereHas('role', function ($query) {
    $query->where('title', 'administrator');
})->get();
```

(untested so use with caution)
