### ISSUE TITLE
How to create new Controller??

### ISSUE THREAD

**Issue by shifatbuet** [LaravelDaily/laravel-roles-permissions-manager#22]
.

**Comment by jeremiaspala** [comment]
Hi, u can create the new controller + View and assign permission?.

**Comment by akramulfata10** [comment]
the controller is not called, maybe you haven't used the controller you are targeting in the web.php file.

#https://stackoverflow.com/questions/63807930/error-target-class-controller-does-not-exist-when-using-laravel-8
