### ISSUE TITLE
User roles will not select in the user edit form

### ISSUE THREAD

**Issue by mshahrokhi** [LaravelDaily/laravel-roles-permissions-manager#24]
I found in the user edit form, user roles must be selected automatically but nothing will select.
Solution is change `$user->roles->contains($id)` to `$user->roles()->pluck('name')->contains($id)` in line 55 in [this](https://github.com/LaravelDaily/laravel-roles-permissions-manager/blob/master/resources/views/admin/users/edit.blade.php) file.

Regards

**Comment by Marius-K** [comment]
Hello @mshahrokhi 

Thank you for the solution, solved.
