### ISSUE TITLE
permisson 

### ISSUE THREAD

**Issue by kaekoko** [LaravelDaily/laravel-roles-permissions-manager#29]
how to do user direct permission?

**Comment by PovilasKorop** [comment]
@kaekoko what do you mean direct?

**Comment by kaekoko** [comment]
i mean  remove via role

**Comment by PovilasKorop** [comment]
@kaekoko still didn't understand, please add more details or attach screenshot

**Comment by kaekoko** [comment]
![localhost_8000_admin_users](https://user-images.githubusercontent.com/40235787/70311524-32f34a00-1840-11ea-90a0-baf610fb7b34.png)

to edit each user permission

**Comment by kaekoko** [comment]
the same role but different permission

**Comment by PovilasKorop** [comment]
@kaekoko oh now I understand. We don't have such feature. I guess the way is to create a new role specifically for that user or set of users.

**Comment by kaekoko** [comment]
Thank  you so much
