### ISSUE TITLE
QUESTION: Update AdminLTE?

### ISSUE THREAD

**Issue by bellwood** [LaravelDaily/laravel-roles-permissions-manager#3]
It appears this project is using AdminLTE 2.3x, the latest version is 2.4.2 as of this writing.

Is there any plans to keep the bouncer/spatie projects up to date?

Thank you =)

**Comment by PovilasKorop** [comment]
Hi @bellwood - thanks for noticing that. These projects was more for demo purposes and not oriented at front-end at all. So I could maybe promise a back-end update for Laravel versions, but AdminLTE is absolutely not the focus of this project.

**Comment by bellwood** [comment]
Without a doubt... Just figured I'd mention it as we'd like to transition an existing/current project to one of these two and we're already using the latest version of AdminLTE... 

I also noticed that AdminLTE wasn't a package required via composer (composer.json) so was unclear as to how we'd would maintain that using this solution.

Never-the-less, appreciate the work involved in making these available to the community =)
