### ISSUE TITLE
XXXXXXX.mass_destroy does not work!!

### ISSUE THREAD

**Issue by Boudani-Aziz** [LaravelDaily/laravel-roles-permissions-manager#31]
Hello Povilas,
I have tested your project, the Mass_Destroy Method does not work. 
there is a message:
Status Code 405 Method Not Allowed.
do you have an idea why that does not work?
Thank you
Boudani
![grafik](https://user-images.githubusercontent.com/42377187/70542499-179e7c80-1b69-11ea-879c-1c4ae6887cab.png)

**Comment by Marius-K** [comment]
Hello @Boudani-Aziz 

Thank you for noticing this error, fixed! Please pull to the latest version if you have cloned the repository

**Comment by Boudani-Aziz** [comment]
Thank you Marius
