### ISSUE TITLE
Relationships are missing

### ISSUE THREAD

**Issue by chisumo2016** [LaravelDaily/laravel-roles-permissions-manager#32]
Hi 
Some of the relationships of the models are missing eg user and role permission and roles . Can you explain why you didn't include other relationships on the project?

**Comment by PovilasKorop** [comment]
@chisumo2016 it's because relationships are inside of the *package* we use, check this source: https://github.com/spatie/laravel-permission/blob/master/src/Models/Role.php

**Comment by chisumo2016** [comment]
Thanks for replying
