### ISSUE TITLE
Route Error

### ISSUE THREAD

**Issue by RicardoMarchesan** [LaravelDaily/laravel-roles-permissions-manager#34]
in 
Route::redirect('/', '/admin/home');
alter to 
Route::redirect('/', 'admin/home');

**Comment by PovilasKorop** [comment]
@RicardoMarchesan this error for you means that you're using this package in a subfolder, like `localhost/something` and I wouldn't advise that, you better configure a proper domain like `project.com` or `project.test` on local.

But anyway, made the fix: https://github.com/LaravelDaily/laravel-roles-permissions-manager/commit/2279403f892aa7f29eeaaf26ff56e7274be23894
