### ISSUE TITLE
Can't edit a user - email is already taken

### ISSUE THREAD

**Issue by duckygator** [LaravelDaily/laravel-roles-permissions-manager#37]
When I try to edit a user to change roles I am unable to save the changes as I get an alert that "The email has already been taken."

**Comment by Marius-K** [comment]
Hello @duckygator 

Thank you for noticing this bug, fixed it. Pull the latest code from repository or make code changes from commit 5d66225 by yourself.

**Comment by duckygator** [comment]
Thanks for the quick fix!
