### ISSUE TITLE
Code Explanation and Tutorial

### ISSUE THREAD

**Issue by saadabdurrazaq** [LaravelDaily/laravel-roles-permissions-manager#38]
I found some difficult to understand this code. So, please give us explanation and tutorial about this code

**Comment by PovilasKorop** [comment]
@saadabdurrazaq which part exactly is not clear to you? I can't give a tutorial about EVERYTHING in this project.

Or, maybe you should read the docs of the underlying package: https://docs.spatie.be/laravel-permission/v3/introduction/

**Comment by saadabdurrazaq** [comment]
For now I am trying to find out about the parts that involved to login page, but I didn't find it

**Comment by PovilasKorop** [comment]
@saadabdurrazaq you didn't find the login page? It's default as in any Laravel project: `resources/views/auth/login.blade.php`: https://github.com/LaravelDaily/laravel-roles-permissions-manager/blob/master/resources/views/auth/login.blade.php

So if you lack knowledge about how Laravel works in general, sorry I can't write a tutorial for that.
