### ISSUE TITLE
Database Migration error 

### ISSUE THREAD

**Issue by Shahjalal7311** [LaravelDaily/laravel-roles-permissions-manager#4]
OS: ubunto 16.04
When run this command 
php artisan migrate --seed
I am getting error.Why this error occurred. Try to learning Laravel.
How can i solve this error?

[Illuminate\Database\QueryException]                                   
  could not find driver (SQL: select * from information_schema.tables w  
  here table_schema = forge and table_name = migrations)                 
                                     
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver                
                                                        
  [PDOException]         
  could not find driver

**Comment by PovilasKorop** [comment]
Something is wrong with your database connection or settings. Please read more about env files and config/database.php settings.
