### ISSUE TITLE
SUGGESTION: Sort based on name, not object id

### ISSUE THREAD

**Issue by bellwood** [LaravelDaily/laravel-roles-permissions-manager#7]
Rather than sort roles/permissions and permission "tags" (when adding to a role) by name, they are sorted by the objects id.

This makes readability poor if you later on decide to add additional permissions (they appear at the end of the list)

Would be nice to have these sorted by name instead.

**Comment by PovilasKorop** [comment]
@bellwood thanks for the suggestion, but we are not planning to actively update this demo project with enhancements like this. But if you offer a pull request, we will happily accept and merge it.

**Comment by bellwood** [comment]
Will do, thanks =)
