### ISSUE TITLE
PHP 7 Issue

### ISSUE THREAD

**Issue by bhargav960143** [LaravelDaily/laravel-roles-permissions-manager#8]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v5.5.9 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.

**Comment by PovilasKorop** [comment]
Yes, Laravel 5.5 requires PHP 7.0 version, see here: https://laravel.com/docs/5.5/installation#server-requirements

**Comment by bhargav960143** [comment]
is there any way to setup in lavavel 5.4.* and php version 5.6.31??

**Comment by PovilasKorop** [comment]
Change it in composer.json to Laravel 5.4 and run composer update, maybe it will work, but cannot guarantee.
