### ISSUE TITLE
Error while composer install

### ISSUE THREAD

**Issue by js5285** [LaravelDaily/laravel-roles-permissions-manager#9]
Hi, 

When I `composer install`, I get error as below: 

`Generating optimized autoload files
Method Illuminate\Foundation\ComposerScripts::postAutoloadDump is not callable, can not call post-autoload-dump script
> @php artisan package:discover

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "package" namespace.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
PS C:\xampp\htdocs\laravel-daily-master>`

How can I solve it? 

Thanks in advances.

**Comment by LaravelDaily** [comment]
Thank you for noticing that, surprised no one reported it before.
We accepted a pull request for Laravel 5.4 -> 5.5 but I forgot to regenerate composer.lock file for that.

Fixed now with this commit: https://github.com/LaravelDaily/laravel-roles-permissions-manager/commit/4acf2d95548544589405a751533eab52cf39f103
